export * from "./AboutUs"
export * from "./ImagesAbout"
export * from "./OurStory"
export * from "./OurStory_nd"
export * from "./ReviewAbout"
export * from "./Slogan"
export * from "./SocialAbout"
export * from "./Welcome"